local Constants = {
	CHARACTERS_COLLISION_GROUP_IDENTIFIER = "__CHARACTERS",
	BYZANTIUM_CHARACTERS_COLLISION_GROUP_IDENTIFIER = "__BYZANTIUM_CHARACTERS",

	CUBES_FOLDER_IDENTIFIER = "__BYZANTIUM_CUBES",
    FAKE_CHARACTERS_FOLDER_IDENTIFIER = "__BYZANTIUM_FAKE_CHARACTERS",

    CUBE_ATTACHMENT_IDENTIFIER = "BYZANTIUM_CUBE_ATTACHMENT",

	EQUIPPED_ATTRIBUTE_IDENTIFIER = "__BYZANTIUM_EQUIPPED",
	ACTION_ATTRIBUTE_IDENTIFIER = "__BYZANTIUM_ACTION",

    ASTRAL_PROJECTION = {
	    -- the attribtue assigned to victims of astral projection while they are in
	    -- the astral dimension
	    PROJECTED_ATTRIBUTE_IDENTIFIER = "__BYZANTIUM_ASTRAL_PROJECTED",

	    -- the attribute momentarily assigned to Byzantium users currently
	    -- projecting someone
	    PROJECTING_ATTRIBUTE_IDENTIFIER = "__BYZANTIUM_ASTRAL_PROJECTING",
    },
}

return Constants